export const ADD_INGRIDIENT = 'ADD_INGRIDIENT';
export const ADD_INGRIDIENT_BUN = 'ADD_INGRIDIENT_BUN';
export const MOVE_INGRIDIENT = 'MOVE_INGRIDIENT';
export const DELETE_INGRIDIENT = 'DELETE_INGRIDIENT';
